/*
 * This file is generated by jOOQ.
*/
package com.crm.corecrm.domain.db.tables.records;


import com.crm.corecrm.domain.db.tables.Chat;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatRecord extends UpdatableRecordImpl<ChatRecord> implements Record6<Integer, Long, String, Integer, Integer, String> {

    private static final long serialVersionUID = 1664455178;

    /**
     * Setter for <code>PUBLIC.CHAT.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CHAT.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CHAT.CHAT_ID</code>.
     */
    public void setChatId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CHAT.CHAT_ID</code>.
     */
    public Long getChatId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CHAT.CHANNEL_TYPE</code>.
     */
    public void setChannelType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CHAT.CHANNEL_TYPE</code>.
     */
    public String getChannelType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CHAT.CREATOR_BY</code>.
     */
    public void setCreatorBy(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CHAT.CREATOR_BY</code>.
     */
    public Integer getCreatorBy() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CHAT.CREATED_AT</code>.
     */
    public void setCreatedAt(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CHAT.CREATED_AT</code>.
     */
    public Integer getCreatedAt() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>PUBLIC.CHAT.STATUS</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.CHAT.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Long, String, Integer, Integer, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Long, String, Integer, Integer, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Chat.CHAT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Chat.CHAT.CHAT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Chat.CHAT.CHANNEL_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Chat.CHAT.CREATOR_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Chat.CHAT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Chat.CHAT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getChatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getChannelType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCreatorBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getChatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getChannelType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCreatorBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatRecord value2(Long value) {
        setChatId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatRecord value3(String value) {
        setChannelType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatRecord value4(Integer value) {
        setCreatorBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatRecord value5(Integer value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatRecord value6(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatRecord values(Integer value1, Long value2, String value3, Integer value4, Integer value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatRecord
     */
    public ChatRecord() {
        super(Chat.CHAT);
    }

    /**
     * Create a detached, initialised ChatRecord
     */
    public ChatRecord(Integer id, Long chatId, String channelType, Integer creatorBy, Integer createdAt, String status) {
        super(Chat.CHAT);

        set(0, id);
        set(1, chatId);
        set(2, channelType);
        set(3, creatorBy);
        set(4, createdAt);
        set(5, status);
    }
}
