/*
 * This file is generated by jOOQ.
*/
package com.crm.corecrm.domain.db.tables.records;


import com.crm.corecrm.domain.db.tables.Dialog;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DialogRecord extends UpdatableRecordImpl<DialogRecord> implements Record4<Integer, Long, Long, String> {

    private static final long serialVersionUID = 1768317928;

    /**
     * Setter for <code>PUBLIC.DIALOG.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.DIALOG.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.DIALOG.CREATOR_BY</code>.
     */
    public void setCreatorBy(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.DIALOG.CREATOR_BY</code>.
     */
    public Long getCreatorBy() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.DIALOG.CREATED_AT</code>.
     */
    public void setCreatedAt(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.DIALOG.CREATED_AT</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>PUBLIC.DIALOG.STATUS</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.DIALOG.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Long, Long, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Long, Long, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Dialog.DIALOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Dialog.DIALOG.CREATOR_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Dialog.DIALOG.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Dialog.DIALOG.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getCreatorBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCreatorBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DialogRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DialogRecord value2(Long value) {
        setCreatorBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DialogRecord value3(Long value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DialogRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DialogRecord values(Integer value1, Long value2, Long value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DialogRecord
     */
    public DialogRecord() {
        super(Dialog.DIALOG);
    }

    /**
     * Create a detached, initialised DialogRecord
     */
    public DialogRecord(Integer id, Long creatorBy, Long createdAt, String status) {
        super(Dialog.DIALOG);

        set(0, id);
        set(1, creatorBy);
        set(2, createdAt);
        set(3, status);
    }
}
