/*
 * This file is generated by jOOQ.
*/
package com.crm.corecrm.domain.db.tables.records;


import com.crm.corecrm.domain.db.tables.OperatorDialog;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OperatorDialogRecord extends UpdatableRecordImpl<OperatorDialogRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -488731894;

    /**
     * Setter for <code>PUBLIC.OPERATOR_DIALOG.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.OPERATOR_DIALOG.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.OPERATOR_DIALOG.OPERATOR_ID</code>.
     */
    public void setOperatorId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.OPERATOR_DIALOG.OPERATOR_ID</code>.
     */
    public Integer getOperatorId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.OPERATOR_DIALOG.CHAT_ID</code>.
     */
    public void setChatId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.OPERATOR_DIALOG.CHAT_ID</code>.
     */
    public Integer getChatId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OperatorDialog.OPERATOR_DIALOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return OperatorDialog.OPERATOR_DIALOG.OPERATOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return OperatorDialog.OPERATOR_DIALOG.CHAT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getOperatorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getChatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOperatorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getChatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperatorDialogRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperatorDialogRecord value2(Integer value) {
        setOperatorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperatorDialogRecord value3(Integer value) {
        setChatId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperatorDialogRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OperatorDialogRecord
     */
    public OperatorDialogRecord() {
        super(OperatorDialog.OPERATOR_DIALOG);
    }

    /**
     * Create a detached, initialised OperatorDialogRecord
     */
    public OperatorDialogRecord(Integer id, Integer operatorId, Integer chatId) {
        super(OperatorDialog.OPERATOR_DIALOG);

        set(0, id);
        set(1, operatorId);
        set(2, chatId);
    }
}
