/*
 * This file is generated by jOOQ.
*/
package com.crm.corecrm.domain.db;


import com.crm.corecrm.domain.db.tables.Chat;
import com.crm.corecrm.domain.db.tables.Customer;
import com.crm.corecrm.domain.db.tables.Message;
import com.crm.corecrm.domain.db.tables.Operator;
import com.crm.corecrm.domain.db.tables.OperatorDialog;
import com.crm.corecrm.domain.db.tables.SchemaVersion;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONSTRAINT_INDEX_1F = Indexes0.CONSTRAINT_INDEX_1F;
    public static final Index PRIMARY_KEY_1F = Indexes0.PRIMARY_KEY_1F;
    public static final Index CONSTRAINT_INDEX_5 = Indexes0.CONSTRAINT_INDEX_5;
    public static final Index CONSTRAINT_INDEX_52 = Indexes0.CONSTRAINT_INDEX_52;
    public static final Index PRIMARY_KEY_5 = Indexes0.PRIMARY_KEY_5;
    public static final Index CONSTRAINT_INDEX_6 = Indexes0.CONSTRAINT_INDEX_6;
    public static final Index PRIMARY_KEY_63 = Indexes0.PRIMARY_KEY_63;
    public static final Index CONSTRAINT_INDEX_1 = Indexes0.CONSTRAINT_INDEX_1;
    public static final Index PRIMARY_KEY_1 = Indexes0.PRIMARY_KEY_1;
    public static final Index CONSTRAINT_INDEX_2 = Indexes0.CONSTRAINT_INDEX_2;
    public static final Index CONSTRAINT_INDEX_27 = Indexes0.CONSTRAINT_INDEX_27;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    public static final Index PRIMARY_KEY_6 = Indexes0.PRIMARY_KEY_6;
    public static final Index SCHEMA_VERSION_IR_IDX = Indexes0.SCHEMA_VERSION_IR_IDX;
    public static final Index SCHEMA_VERSION_S_IDX = Indexes0.SCHEMA_VERSION_S_IDX;
    public static final Index SCHEMA_VERSION_VR_IDX = Indexes0.SCHEMA_VERSION_VR_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONSTRAINT_INDEX_1F = Internal.createIndex("CONSTRAINT_INDEX_1F", Chat.CHAT, new OrderField[] { Chat.CHAT.TG_CHAT_ID }, true);
        public static Index PRIMARY_KEY_1F = Internal.createIndex("PRIMARY_KEY_1F", Chat.CHAT, new OrderField[] { Chat.CHAT.ID }, true);
        public static Index CONSTRAINT_INDEX_5 = Internal.createIndex("CONSTRAINT_INDEX_5", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.TG_ID }, true);
        public static Index CONSTRAINT_INDEX_52 = Internal.createIndex("CONSTRAINT_INDEX_52", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.FIRSTNAME }, true);
        public static Index PRIMARY_KEY_5 = Internal.createIndex("PRIMARY_KEY_5", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.ID }, true);
        public static Index CONSTRAINT_INDEX_6 = Internal.createIndex("CONSTRAINT_INDEX_6", Message.MESSAGE, new OrderField[] { Message.MESSAGE.CHAT_ID }, false);
        public static Index PRIMARY_KEY_63 = Internal.createIndex("PRIMARY_KEY_63", Message.MESSAGE, new OrderField[] { Message.MESSAGE.ID }, true);
        public static Index CONSTRAINT_INDEX_1 = Internal.createIndex("CONSTRAINT_INDEX_1", Operator.OPERATOR, new OrderField[] { Operator.OPERATOR.LOGIN }, true);
        public static Index PRIMARY_KEY_1 = Internal.createIndex("PRIMARY_KEY_1", Operator.OPERATOR, new OrderField[] { Operator.OPERATOR.ID }, true);
        public static Index CONSTRAINT_INDEX_2 = Internal.createIndex("CONSTRAINT_INDEX_2", OperatorDialog.OPERATOR_DIALOG, new OrderField[] { OperatorDialog.OPERATOR_DIALOG.OPERATOR_ID }, false);
        public static Index CONSTRAINT_INDEX_27 = Internal.createIndex("CONSTRAINT_INDEX_27", OperatorDialog.OPERATOR_DIALOG, new OrderField[] { OperatorDialog.OPERATOR_DIALOG.CHAT_ID }, false);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", OperatorDialog.OPERATOR_DIALOG, new OrderField[] { OperatorDialog.OPERATOR_DIALOG.ID }, true);
        public static Index PRIMARY_KEY_6 = Internal.createIndex("PRIMARY_KEY_6", SchemaVersion.SCHEMA_VERSION, new OrderField[] { SchemaVersion.SCHEMA_VERSION.VERSION }, true);
        public static Index SCHEMA_VERSION_IR_IDX = Internal.createIndex("schema_version_ir_idx", SchemaVersion.SCHEMA_VERSION, new OrderField[] { SchemaVersion.SCHEMA_VERSION.INSTALLED_RANK }, false);
        public static Index SCHEMA_VERSION_S_IDX = Internal.createIndex("schema_version_s_idx", SchemaVersion.SCHEMA_VERSION, new OrderField[] { SchemaVersion.SCHEMA_VERSION.SUCCESS }, false);
        public static Index SCHEMA_VERSION_VR_IDX = Internal.createIndex("schema_version_vr_idx", SchemaVersion.SCHEMA_VERSION, new OrderField[] { SchemaVersion.SCHEMA_VERSION.VERSION_RANK }, false);
    }
}
