/*
 * This file is generated by jOOQ.
*/
package com.crm.corecrm.domain.db;


import com.crm.corecrm.domain.db.tables.Dialog;
import com.crm.corecrm.domain.db.tables.Message;
import com.crm.corecrm.domain.db.tables.Operator;
import com.crm.corecrm.domain.db.tables.OperatorDialog;
import com.crm.corecrm.domain.db.tables.SchemaVersion;
import com.crm.corecrm.domain.db.tables.records.DialogRecord;
import com.crm.corecrm.domain.db.tables.records.MessageRecord;
import com.crm.corecrm.domain.db.tables.records.OperatorDialogRecord;
import com.crm.corecrm.domain.db.tables.records.OperatorRecord;
import com.crm.corecrm.domain.db.tables.records.SchemaVersionRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DialogRecord, Integer> IDENTITY_DIALOG = Identities0.IDENTITY_DIALOG;
    public static final Identity<MessageRecord, Integer> IDENTITY_MESSAGE = Identities0.IDENTITY_MESSAGE;
    public static final Identity<OperatorRecord, Integer> IDENTITY_OPERATOR = Identities0.IDENTITY_OPERATOR;
    public static final Identity<OperatorDialogRecord, Integer> IDENTITY_OPERATOR_DIALOG = Identities0.IDENTITY_OPERATOR_DIALOG;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DialogRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;
    public static final UniqueKey<MessageRecord> CONSTRAINT_6 = UniqueKeys0.CONSTRAINT_6;
    public static final UniqueKey<OperatorRecord> CONSTRAINT_1 = UniqueKeys0.CONSTRAINT_1;
    public static final UniqueKey<OperatorRecord> CONSTRAINT_10 = UniqueKeys0.CONSTRAINT_10;
    public static final UniqueKey<OperatorDialogRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
    public static final UniqueKey<SchemaVersionRecord> SCHEMA_VERSION_PK = UniqueKeys0.SCHEMA_VERSION_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MessageRecord, DialogRecord> CONSTRAINT_63 = ForeignKeys0.CONSTRAINT_63;
    public static final ForeignKey<OperatorDialogRecord, OperatorRecord> CONSTRAINT_27 = ForeignKeys0.CONSTRAINT_27;
    public static final ForeignKey<OperatorDialogRecord, DialogRecord> CONSTRAINT_274 = ForeignKeys0.CONSTRAINT_274;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DialogRecord, Integer> IDENTITY_DIALOG = Internal.createIdentity(Dialog.DIALOG, Dialog.DIALOG.ID);
        public static Identity<MessageRecord, Integer> IDENTITY_MESSAGE = Internal.createIdentity(Message.MESSAGE, Message.MESSAGE.ID);
        public static Identity<OperatorRecord, Integer> IDENTITY_OPERATOR = Internal.createIdentity(Operator.OPERATOR, Operator.OPERATOR.ID);
        public static Identity<OperatorDialogRecord, Integer> IDENTITY_OPERATOR_DIALOG = Internal.createIdentity(OperatorDialog.OPERATOR_DIALOG, OperatorDialog.OPERATOR_DIALOG.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DialogRecord> CONSTRAINT_7 = Internal.createUniqueKey(Dialog.DIALOG, "CONSTRAINT_7", Dialog.DIALOG.ID);
        public static final UniqueKey<MessageRecord> CONSTRAINT_6 = Internal.createUniqueKey(Message.MESSAGE, "CONSTRAINT_6", Message.MESSAGE.ID);
        public static final UniqueKey<OperatorRecord> CONSTRAINT_1 = Internal.createUniqueKey(Operator.OPERATOR, "CONSTRAINT_1", Operator.OPERATOR.ID);
        public static final UniqueKey<OperatorRecord> CONSTRAINT_10 = Internal.createUniqueKey(Operator.OPERATOR, "CONSTRAINT_10", Operator.OPERATOR.LOGIN);
        public static final UniqueKey<OperatorDialogRecord> CONSTRAINT_2 = Internal.createUniqueKey(OperatorDialog.OPERATOR_DIALOG, "CONSTRAINT_2", OperatorDialog.OPERATOR_DIALOG.ID);
        public static final UniqueKey<SchemaVersionRecord> SCHEMA_VERSION_PK = Internal.createUniqueKey(SchemaVersion.SCHEMA_VERSION, "schema_version_pk", SchemaVersion.SCHEMA_VERSION.VERSION);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<MessageRecord, DialogRecord> CONSTRAINT_63 = Internal.createForeignKey(com.crm.corecrm.domain.db.Keys.CONSTRAINT_7, Message.MESSAGE, "CONSTRAINT_63", Message.MESSAGE.DIALOG_ID);
        public static final ForeignKey<OperatorDialogRecord, OperatorRecord> CONSTRAINT_27 = Internal.createForeignKey(com.crm.corecrm.domain.db.Keys.CONSTRAINT_1, OperatorDialog.OPERATOR_DIALOG, "CONSTRAINT_27", OperatorDialog.OPERATOR_DIALOG.SUPPORT_ID);
        public static final ForeignKey<OperatorDialogRecord, DialogRecord> CONSTRAINT_274 = Internal.createForeignKey(com.crm.corecrm.domain.db.Keys.CONSTRAINT_7, OperatorDialog.OPERATOR_DIALOG, "CONSTRAINT_274", OperatorDialog.OPERATOR_DIALOG.DIALOG_ID);
    }
}
