/*
 * This file is generated by jOOQ.
*/
package com.crm.corecrm.domain.db;


import com.crm.corecrm.domain.db.tables.Dialog;
import com.crm.corecrm.domain.db.tables.Message;
import com.crm.corecrm.domain.db.tables.Operator;
import com.crm.corecrm.domain.db.tables.OperatorDialog;
import com.crm.corecrm.domain.db.tables.SchemaVersion;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1062213457;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.DIALOG</code>.
     */
    public final Dialog DIALOG = com.crm.corecrm.domain.db.tables.Dialog.DIALOG;

    /**
     * The table <code>PUBLIC.MESSAGE</code>.
     */
    public final Message MESSAGE = com.crm.corecrm.domain.db.tables.Message.MESSAGE;

    /**
     * The table <code>PUBLIC.OPERATOR</code>.
     */
    public final Operator OPERATOR = com.crm.corecrm.domain.db.tables.Operator.OPERATOR;

    /**
     * The table <code>PUBLIC.OPERATOR_DIALOG</code>.
     */
    public final OperatorDialog OPERATOR_DIALOG = com.crm.corecrm.domain.db.tables.OperatorDialog.OPERATOR_DIALOG;

    /**
     * The table <code>PUBLIC.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = com.crm.corecrm.domain.db.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Dialog.DIALOG,
            Message.MESSAGE,
            Operator.OPERATOR,
            OperatorDialog.OPERATOR_DIALOG,
            SchemaVersion.SCHEMA_VERSION);
    }
}
